[package]
name = "fs_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
inotify = "0.11.0"
futures = "0.3.30"
notify = "7.0.0"
sha2 = "0.10.0"
dashmap = "6.1.0"
glob = "0.3.2"
tempfile = "3.17.1"
sha3 = "0.10.8"
tokio = { version = "1.36.0", features = ["full"] }